spring:
  application:
    name: config
  profiles:
    active: docker
server:
  port: 8700
---
spring:
  profiles: docker
  cloud:
    config:
      server:
        git:
          uri: https://github.com/li-hongjie/springclouddemo-config.git
  rabbitmq:
    host: 192.168.37.101
    port: 5672
    username: spring
    password: spring
---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  rabbitmq:
    host: 192.168.37.101
    port: 5672
    username: spring
    password: spring